<h1 style="text-align: center;">Prueba - Income</h1>

Usted trabaja para un organismo no gubernamental que está interesado en las dinámicas
socioeconómicas que determinan la desigualdad de ingreso y la erradicación de la pobreza
extrema, enmarcado dentro de los objetivos del desarrollo del nuevo milenio del Programa
de las Naciones Unidas para el Desarrollo.

Le encomiendan el desarrollo de un modelo predictivo sobre la probabilidad que un individuo
presente salarios por sobre o bajo los 50.000 dólares anuales, en base a una serie de
atributos sociodemográficos.

## Descripción


<p> Para desarrollar este desafío se debe utilizar la base de datos income-db.csv. </p>

<p> Las variables que componen esta base se detallan a continuación: </p>

- `age`: Edad del individuo.

- `workclass`: Naturaleza de la organización que emplea al individuo.

- `education`: Nivel educacional del individuo:Bachelors (Licenciado), Some-college
(Superior incompleta), 11th (3ro medio), HS-grad (Secundaria completa), Prof-school
(Escuela profesional), Assoc-acdm (Técnico superior administrativo) , Assoc-voc
(Técnico superior vocacional), 9th (1ro medio), 7th-8th (7mo-8vo), 12th (4to medio),
Masters (Maestría de postgrado), 1st-4th (1ro-4to básico), 10th(2do medio),
Doctorate (Doctorado), 5th-6th (5to-6to), Preschool (Preescolar).

- `capital-gains`: Ingresos generados por inversiones fuera del trabajo asalariado =
Ingresos generados por inversiones fuera del trabajo asalariado.

- `capital-losses`: Pérdidas generadas por inversiones fuera del trabajo asalariado.
- `fnlwgt`: Ponderador muestral.

- `marital-status`: Estado civil del individuo: Married-civ-spouse (Casado/a régimen
civil), Divorced (Divorciado/a), Never-married (Soltero/a), Separated (Separado/a),
Widowed (Viudo/a), Married-spouse-absent (Casado con esposo/a ausente),
Married-AF-spouse (Casado/a régimen castrense).

- `occupation`: Ocupación del individuo: Tech-support (Soporte técnico), Craft-repair
(Reparaciones), Other-service (Otros servicios), Sales (Ventas), Exec-managerial
(Ejecutivo administrativos), Prof-specialty (Profesores), Handlers-cleaners (Aseo y
ornato), Machine-op-inspct (Inspectores de maquinarias), Adm-clerical
(Administrativos servicio al cliente), Farming-fishing (Pesca-ganadería),
Transport-moving (Transporte), Priv-house-serv (Asesor del hogar), Protective-serv
(servicios de seguridad), Armed-Forces (Fuerzas armadas).

- `relationship`: Relación respecto a su familia Wife(Esposa), Own-child (hijo único),
Husband (Esposo), Not-in-family (No pertenece a la familia), Other-relative (Familiar
de otro tipo), Unmarried (Soltero).

- `race`: Raza del encuestado White(Blanco caucásico), Asian-Pac-Islander (Isleño del
Asia Pacífico), Amer-Indian-Eskimo (Pertenenciente a pueblos originarios), Other
(Otro grupo), Black (Afroamericano).

- `sex`: Sexo del encuestado.

- `hours-per-week`: Cantidad de horas trabajadas por semana.

- `native-country`: País de origen. United-States, Cambodia, England, Puerto-Rico,
Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China,
Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal,
Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary,
Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago,
Peru, Hong, Holand-Netherlands.

- `income`: <=50K Si el individuo percibe ingresos inferiores a 50.000 dólares anuales,
>50K si el individuo percibe ingresos superiores a 50.000 dólares anuales. Este es su
vector objetivo.

### Hito 1


<img src="hito1.png"  width="900" height="900" alt="">

In [5]:
# Utiliza esta celda para importar los módulos solicitados y el set de datos

import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

#df = pd.read_csv("default_credit.csv").drop(columns="index", axis=1)


df = pd.read_csv("income-db.csv")

df.head(5)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [7]:
df.shape

(48842, 15)